-- Add title and output columns to tasks table
-- title: Short human-readable identifier for the task (generated by manager agent)
-- output: Summary of what the ralph agent accomplished (populated after completion)

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tasks' AND column_name = 'title') THEN
        ALTER TABLE public.tasks ADD COLUMN title text;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tasks' AND column_name = 'output') THEN
        ALTER TABLE public.tasks ADD COLUMN output text;
    END IF;
END $$;
